DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS COMPOSITION;
DROP TABLE IF EXISTS PERFORMANCE;
DROP TABLE IF EXISTS PERFORMANCE_PARTICIPANTS;

create table INSTRUMENT (

  ID int not null auto_increment,
  TYPE varchar (15) not null,
  PRODUCER varchar (30) not null,
  PROD_DATE datetime not null,
  PURCH_DATE datetime not null,
  PRIMARY KEY (ID)
);

create table STUDENT (

  ID int not null auto_increment,
  INSTRUMENT_ID int not null,
  FIRST_NAME varchar (40) not null,
  LAST_NAME varchar (40) not null,
  BIRTH_DATE datetime not null,
  PRIMARY KEY (ID),
  UNIQUE (FIRST_NAME, LAST_NAME),
  CONSTRAINT FK_STUDENT_INSTRUMENT
  FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENT (ID)
);

create table COMPOSITION (
  ID int not null auto_increment,
  TITLE varchar(25) not null,
  AUTHOR varchar(50) not null,
  PRIMARY KEY (ID)
);

create table PERFORMANCE (

  ID int not null auto_increment,
  COMPOSITION_ID int not null,
  PRIMARY KEY (ID),
  CONSTRAINT FK_PERFORMANCE_COMPOSITION
  FOREIGN KEY (COMPOSITION_ID) REFERENCES COMPOSITION (ID)
);

create table PERFORMANCE_PARTICIPANTS (

  PERFORMANCE_ID int not null,
  STUDENT_ID int not null,
  PRIMARY KEY (PERFORMANCE_ID, STUDENT_ID),
  CONSTRAINT FK_PERFORMANCE_PARTICIPANTS_PERFORMANCE
  FOREIGN KEY (PERFORMANCE_ID) REFERENCES PERFORMANCE (ID),
  CONSTRAINT FK_PERFORMANCE_PARTICIPANTS_STUDENT
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID)
);